apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/USER/Desktop/DRL_PO_OCS/mlops-drl-portfolio/local-storage/minio"
  claimRef:
    namespace: default
    name: minio-pvc
