apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/USER/Desktop/DRL_PO_OCS/mlops-drl-portfolio/local-storage/neo4j"
  claimRef:
    namespace: default
    name: neo4j-pvc
