apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  # IMPORTANT: Change these default credentials for any real deployment
  POSTGRES_USER: "airflow"
  POSTGRES_PASSWORD: "airflow"
