apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  # IMPORTANT: Change these default credentials for any real deployment
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
