apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false # Prevents k8s from injecting service env vars that confuse Neo4j
      containers:
        - name: neo4j
          image: neo4j:5-community
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: NEO4J_AUTH
            # Required to accept the license agreement
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
          ports:
            - containerPort: 7474 # HTTP
            - containerPort: 7687 # Bolt
          volumeMounts:
            - name: neo4j-storage
              mountPath: /data
      volumes:
        - name: neo4j-storage
          persistentVolumeClaim:
            claimName: neo4j-pvc
